# Generated by Django 5.1.2 on 2024-11-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='storage',
        ),
    ]
