# Generated by Django 5.1.3 on 2024-11-15 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_build_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cpu/'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/motherboard/'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ram/'),
        ),
        migrations.AddField(
            model_name='ram',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/storage/'),
        ),
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
