# Generated by Django 5.1.2 on 2024-11-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_shopping_cart_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='storage_form_factor',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='storage_form_factor',
            field=models.ManyToManyField(to='home.storageformfactor'),
        ),
    ]
