# Generated by Django 5.1.3 on 2024-11-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cpu_image_cpu_price_motherboard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
