# Generated by Django 5.1.3 on 2024-11-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cpu_description_motherboard_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='name',
            field=models.CharField(default='Default Build Name', max_length=100),
        ),
    ]
