# Generated by Django 5.1.3 on 2024-11-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_build',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profile', to='home.build'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['is_active'], name='home_build_is_acti_5e7cdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.CheckConstraint(condition=models.Q(('is_active__in', [True, False])), name='is_active_valid'),
        ),
    ]
