# Generated by Django 5.1.3 on 2024-11-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_build_is_active_profile_current_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=50)),
                ('part_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='home.shoppingcart')),
            ],
        ),
    ]
