# Generated by Django 5.1.3 on 2024-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_shoppingcart_items_shoppingcart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
